name: barangqrcode
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.6
  open_file_plus: ^3.4.1+1
  path_provider: ^2.0.11
  pdf: ^3.3.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-Regular.ttf
